### PR TITLE
Warnings

### PR DESCRIPTION
**Pull request by utilum**
Removes some leftover dead code and avoids some warnings. See commit messages for details.

### CODE REVIEW

**Comment by rsl** [comment]
where were these warnings coming from? ruby or a linter? looks good to me though. sorry i missed email about this 11 days ago apparently.

**Comment by utilum** [comment]
Thank you for looking, @rsl . The warnings come from Ruby with warnings enabled. Here's master with warnings enabled:

```
$ git diff
diff --git a/Rakefile b/Rakefile
index 505511f..0ae870c 100644
--- a/Rakefile
+++ b/Rakefile
@@ -31,7 +31,7 @@ Rake::TestTask.new do |t|
   t.libs << 'lib' << 'test'
   t.pattern   = 'test/unit/**/*_test.rb'
   t.verbose   = false
-  t.warning   = false
+  t.warning   = true
 end
 
 namespace :test do
$ $ bundle exec rake test 2>&1 | grep ': warning:' | grep 'lib\/stringex' | sort | uniq | grep -v 'not initialized' 
./stringex/lib/stringex/acts_as_url/adapter/data_mapper.rb:43: warning: previous definition of read_attribute was here
./stringex/lib/stringex/acts_as_url/adapter/data_mapper.rb:51: warning: method redefined; discarding old read_attribute
===============================================================================./stringex/lib/stringex/acts_as_url.rb:59: warning: method redefined; discarding old acts_as_url_configuration
./stringex/lib/stringex/acts_as_url.rb:59: warning: method redefined; discarding old acts_as_url_configuration
./stringex/lib/stringex/acts_as_url.rb:59: warning: method redefined; discarding old acts_as_url_configuration=
../stringex/lib/stringex/acts_as_url.rb:59: warning: method redefined; discarding old acts_as_url_configuration
...../stringex/lib/stringex/acts_as_url.rb:59: warning: method redefined; discarding old acts_as_url_configuration
./stringex/lib/stringex/acts_as_url.rb:62: warning: method redefined; discarding old acts_as_url_configuration
./stringex/lib/stringex/acts_as_url.rb:62: warning: previous definition of acts_as_url_configuration was here
./stringex/lib/stringex/acts_as_url.rb:7: warning: `&' interpreted as argument prefix
./stringex/lib/stringex/localization/backend/i18n.rb:50: warning: assigned but unused variable - path
./stringex/lib/stringex/localization/conversion_expressions.rb:94: warning: character class has duplicated range: /[\w:_-]+/
./stringex/lib/stringex/localization/conversion_expressions.rb:96: warning: character class has duplicated range
./stringex/lib/stringex/localization/conversion_expressions.rb:97: warning: character class has duplicated range
./stringex/lib/stringex/localization/converter.rb:40: warning: ambiguous first argument; put parentheses or a space even after `/' operator
...................................../stringex/lib/stringex/localization/converter.rb:53: warning: character class has duplicated range
./stringex/lib/stringex/localization.rb:86: warning: `&' interpreted as argument prefix
./stringex/lib/stringex/string_extensions.rb:6: warning: `&' interpreted as argument prefix
$
```

**Comment by utilum** [comment]
PS, this leaves: 
 - Method redefined warnings about `acts_as_url_configuration`, I'm confused by the code there, but would be happy to learn.
 - Several instance variable not initialized warnings, I'm not sure about fixing those as fixes risk being ugly.

**Comment by rsl** [comment]
cool. changes look good. happy to merge.

**Comment by rsl** [comment]
hahaha i closed without merging first heh

**Pull request merged**
