### PR TITLE
Add url_taken_method option for overriding url collision logic

### PR DESCRIPTION
**Pull request by joekur**
I want to supply my own method that decides whether a given url candidate is unique or not. Our use-case is that we are also storing histories of urls, for which we do redirects, and we don't want collisions with those as well.

Example:
```
class Document
  acts_as_url :title, url_taken_method: :url_taken?

  def url_taken?(url)
    Document.where(url: url).where("id != ?, id).any? ||
      OtherThingy.where(url: url).any?
  end
end
```

Let me know your thoughts :)

### CODE REVIEW

**Comment by rsl** [comment]
i like idea. not sure about naming. thoughts? sorry about slow reply as well.

**Comment by joekur** [comment]
Hey, thanks for responding. Some other naming ideas: `url_taken_if`, `validate_uniqueness` (would probably switch the meaning of true/false response)

**Comment by rsl** [comment]
what about uniqueness_test or uniqueness_check? perhaps the latter.

**Comment by joekur** [comment]
Yeah I'm ok with that. Returns false if it is not unique?

**Comment by rsl** [comment]
should be optional and default to existing, no?

**Comment by joekur** [comment]
Yes I agree with that. I was commenting on how in my implementation the behavior of a "url_taken_method" made sense to return true if it the url is not unique. To me, if the name were "uniqueness_check", it seems it may instead be more intuitive that your custom method should return false if the url is not unique.

**Comment by rsl** [comment]
perhaps custom_uniqueness_check then? i see what you meant. ;)

**Comment by rsl** [comment]
merged and released as 2.6.0.

**Pull request merged**
